### ISSUE TITLE
Empty Chips in Backing Type

### ISSUE THREAD

**Issue by Mctalian** [YashdalfTheGray/flintandsteel#33]
If you type anything and hit `Enter` whether it is in the list of the backing types or not, it creates an empty "chip".

Steps to reproduce:
1. Login
2. Create an idea
3. View that idea
4. Click on backers
5. Type in some text so that the `Type of backing` field appears.
6. Type: "Time" and hit `Enter`
7. Notice a blank chip has been created.

I think this might be an error with angular-material though. [angular-material issue#2982](https://github.com/angular/material/issues/2982) I tried to make the change that the issue submitter referenced, but it didn't seem to work.

I also was unable to reproduce this via this [codepen](http://codepen.io/anon/pen/aOpRNN) which stemmed from [this example](https://material.angularjs.org/latest/#/demo/material.components.chips).

**Comment by YashdalfTheGray** [comment]
I saw that too and I fixed it in one of the new commits. When did you last pull?

I have also updated angular to 1.4 and angular-material to 0.9.6 so you might need to run `gulp clean:modules` and then `npm install` just to make sure we're on the same versions of everything. 

Try that and let me know.

**Comment by Mctalian** [comment]
This was my first time ever pulling the project down and it looks like I pulled down the latest on `master` at the time. So whatever was the latest on Sunday is where I saw the behavior.

I can still try this later today.

**Comment by YashdalfTheGray** [comment]
Yeah, give it a shot tonight. I've updated a few things here and there. Also be sure to run `gulp clean:modules` and then `npm install` before testing.

**Comment by Mctalian** [comment]
I am still seeing this and #34 after creating a new branch based on commit af865c5 after issuing a `gulp clean:modules` and then `npm install`
